#pragma once

#ifndef ERRORCODES__H
#define ERRORCODES__H

#define ERROR_CODE_something										0x01
#define ERROR_CODE_SETTING_CURRENTSCENE_WHEN_SCENES_IS_EMPTY		0x02
#define ERROR_CODE_SEARCHING_FOR_UNKNOWN_SCENE_ID					0x03

#endif