#pragma once

#ifndef ERRORCODES__H
#define ERRORCODES__H

#define ERROR_CODE_something										0x01
#define ERROR_CODE_SCENE_NO_OBJECT_FOUND							0x02


#define ERROR_CODE_SCENEMANAGER_NO_CURRENT_SCENE					0x10
#define ERROR_CODE_SCENEMANAGER_SCENE_ALREADY_EXISTS				0x11
#define ERROR_CODE_SCENEMANAGER_SCENES_IS_EMPTY						0x12
#define ERROR_CODE_SCENEMANAGER_CANT_FIND_SCENE_WITH_ID				0x13

#define ERROR_CODE_SVIFACADE_CANT_CREATE_RENDERER					0x20
#define ERROR_CODE_SVIFACADE_CANT_CREATE_WINDOW						0x21
#define ERROR_CODE_SVIFACADE_CANT_INITIALIZE_SDL_IMAGE				0x22
#define ERROR_CODE_SVIFACADE_LOADIMAGE_SPRITE_ID_IS_NULL			0x23
#define ERROR_CODE_SVIFACADE_FILENAME_IS_NULL						0x24
#define ERROR_CODE_SVIFACADE_RENDERCOPY_SPRITE_ID_IS_NULL			0x25
#define ERROR_CODE_SVIFACADE_RENDERCOPY_XPOS_IS_NULL				0x26
#define ERROR_CODE_SVIFACADE_RENDERCOPY_YPOS_IS_NULL				0x27
#define ERROR_CODE_SVIFACADE_RENDERCOPY_HEIGHT_IS_NULL				0x28
#define ERROR_CODE_SVIFACADE_RENDERCOPY_WIDTH_IS_NULL				0x29
#define ERROR_CODE_SVIFACADE_RENDERCOPY_ROTATION_IS_NULL			0x2A

#endif

static const char* ERRORCODES[] =
{
	"ERROR_CODE_something",
	"ERROR_CODE_SCENE_NO_OBJECT_FOUND",
	"ERROR_CODE_SCENEMANAGER_NO_CURRENT_SCENE",
	"ERROR_CODE_SCENEMANAGER_SCENE_ALREADY_EXISTS",
	"ERROR_CODE_SCENEMANAGER_SCENES_IS_EMPTY",
	"ERROR_CODE_SCENEMANAGER_CANT_FIND_SCENE_WITH_ID",
	"ERROR_CODE_SVIFACADE_CANT_CREATE_RENDERER",
	"ERROR_CODE_SVIFACADE_CANT_CREATE_WINDOW",
	"ERROR_CODE_SVIFACADE_CANT_INITIALIZE_SDL_IMAGE",
	"ERROR_CODE_SVIFACADE_LOADIMAGE_SPRITE_ID_IS_NULL",
	"ERROR_CODE_SVIFACADE_FILENAME_IS_NULL"
	"ERROR_CODE_SVIFACADE_RENDERCOPY_SPRITE_ID_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_XPOS_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_YPOS_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_HEIGHT_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_WIDTH_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_ROTATION_IS_NULL"
};
