#pragma once

#ifndef ERRORCODES__H
#define ERRORCODES__H

#define ERROR_CODE_something										0x00
#define ERROR_CODE_SCENE_NO_OBJECT_FOUND							0x01


#define ERROR_CODE_SCENEMANAGER_NO_CURRENT_SCENE					0x02
#define ERROR_CODE_SCENEMANAGER_SCENE_ALREADY_EXISTS				0x03
#define ERROR_CODE_SCENEMANAGER_SCENES_IS_EMPTY						0x04
#define ERROR_CODE_SCENEMANAGER_CANT_FIND_SCENE_WITH_ID				0x05

#define ERROR_CODE_SVIFACADE_CANT_CREATE_RENDERER					0x06
#define ERROR_CODE_SVIFACADE_CANT_CREATE_WINDOW						0x07
#define ERROR_CODE_SVIFACADE_CANT_INITIALIZE_SDL_IMAGE				0x08
#define ERROR_CODE_SVIFACADE_LOADIMAGE_SPRITE_ID_IS_NULL			0x09
#define ERROR_CODE_SVIFACADE_FILENAME_IS_NULL						0x0A
#define ERROR_CODE_SVIFACADE_RENDERCOPY_SPRITE_ID_IS_NULL			0x0B
#define ERROR_CODE_SVIFACADE_RENDERCOPY_XPOS_IS_NULL				0x0C
#define ERROR_CODE_SVIFACADE_RENDERCOPY_YPOS_IS_NULL				0x0D
#define ERROR_CODE_SVIFACADE_RENDERCOPY_HEIGHT_IS_NULL				0x0E
#define ERROR_CODE_SVIFACADE_RENDERCOPY_WIDTH_IS_NULL				0x0F
#define ERROR_CODE_SVIFACADE_RENDERCOPY_ROTATION_IS_NULL			0x10

#define PHYSICS_ENGINE_OBJECT_DOESNT_EXIST							0x11
#define PHYSICS_FACADE_OBJECT_DOESNT_EXIST							0x12
#define PHYSICS_FACADE_BODY_DOESNT_EXIST							0x13


#define ERROR_CODE_SVIFACADE_SOUND_FILE_NOT_FOUND					0x30
#define ERROR_CODE_SVIFACADE_SOUND_IDENTIFIER_NOT_FOUND				0x31
#define ERROR_CODE_SVIFACADE_NO_MUSIC_LOADED						0x31
#define ERROR_CODE_SVIFACADE_INVALID_FADETIME						0x31

#endif

static const char* ERRORCODES[] =
{
	"ERROR_CODE_something",
	"ERROR_CODE_SCENE_NO_OBJECT_FOUND",
	"ERROR_CODE_SCENEMANAGER_NO_CURRENT_SCENE",
	"ERROR_CODE_SCENEMANAGER_SCENE_ALREADY_EXISTS",
	"ERROR_CODE_SCENEMANAGER_SCENES_IS_EMPTY",
	"ERROR_CODE_SCENEMANAGER_CANT_FIND_SCENE_WITH_ID",
	"ERROR_CODE_SVIFACADE_CANT_CREATE_RENDERER",
	"ERROR_CODE_SVIFACADE_CANT_CREATE_WINDOW",
	"ERROR_CODE_SVIFACADE_CANT_INITIALIZE_SDL_IMAGE",
	"ERROR_CODE_SVIFACADE_LOADIMAGE_SPRITE_ID_IS_NULL",
	"ERROR_CODE_SVIFACADE_FILENAME_IS_NULL"
	"ERROR_CODE_SVIFACADE_RENDERCOPY_SPRITE_ID_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_XPOS_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_YPOS_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_HEIGHT_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_WIDTH_IS_NULL",
	"ERROR_CODE_SVIFACADE_RENDERCOPY_ROTATION_IS_NULL",
	"ERROR_CODE_SVIFACADE_SOUND_FILE_NOT_FOUND",
	"ERROR_CODE_SVIFACADE_IDENTIFIER_NOT_FOUND"
};
